### ISSUE TITLE
DuplicationOptions: Missing support for Bitwise-OR operator |

### ISSUE THREAD

**Issue by rbu9fe** [CESNET/libyang-cpp#18] opened 2023-11-21 12:46 UTC
In contrast to other enumeration types `DuplicationOptions` doesn't support bitwise-OR `|` even though it says it's supported: `Wraps LY_DUP_* flags. Supports operator|.` It's simply missing in the list where operators are defined.

Also please note the typo in the description, it should read `LYD_DUP_*` rather than `LY_DUP_*`.

**Comment by jktjkt** [comment] 2023-11-21 13:40
Thanks, this patch series should fix that (please feel free to add feedback via Gerrit if you feel like doing that):

- [add missing LYD_DUP_* flags](https://gerrit.cesnet.cz/c/CzechLight/libyang-cpp/+/6663)
- [docs: fix a typo in LYD_DUP_* enum](https://gerrit.cesnet.cz/c/CzechLight/libyang-cpp/+/6664)
- [Add missing operator| for LYD_DUP_*](https://gerrit.cesnet.cz/c/CzechLight/libyang-cpp/+/6665)

**Comment by jktjkt** [comment] 2023-11-21 14:14
Fixed, merged, thanks for reporting this.

**Closed by jktjkt** 2023-11-21 14:14 UTC

**Comment by rbu9fe** [comment] 2023-11-21 14:32
Thanks for the quick fix!

**Comment by rbu9fe** [comment] 2023-11-21 15:35
Sorry but now when building I receive this error:
`.../src/utils/enum.hpp:90:15: error: ‘LYD_DUP_WITH_PRIV’ was not declared in this scope; did you mean ‘LYD_DUP_WITH_PARENTS’?`

**Comment by jktjkt** [comment] 2023-11-21 15:37
You need the latest `devel` of libyang, I guess we forgot to bump the requirement in CMake. That trailing comma is there by design to minimize future diffing.

**Comment by rbu9fe** [comment] 2023-11-21 15:41
CMake is referring to `libyang>=2.1.124`.
I'm using 2.1.124. Do I need to bump to 2.1.128?

**Comment by jktjkt** [comment] 2023-11-21 15:50
yes

**Comment by jktjkt** [comment] 2023-11-21 15:58
actually, my recent build was against libyang 2.1.134, and the latest one upstream is 2.1.139

**Comment by rbu9fe** [comment] 2023-11-21 15:59
That still fails with the same error. I don't know if I'm missing something but the master branch doesn't know `LYD_DUP_WITH_PRIV`:
See https://github.com/CESNET/libyang/blob/master/src/tree_data.h#L1906C19-L1906C19

**Comment by jktjkt** [comment] 2023-11-29 07:57
(fixed via CMake's minimal required version of libyang once again)
